### ISSUE TITLE
General Task List

### ISSUE THREAD

**Issue by jeffcpina** [jeffcpina/pf2e-char-builder#1]
- [ ] spellbuilder.mjs - dropActorSheetData is not working 100%
- [ ] remove compendium builder enhancer and make its own module
- [ ] add requirement to compendium builder enhancer module
